config/routes.rb
Rails.application.routes.draw do

  resources :foods do
    resources :ratings
  end
  resources :restaurants
  resources :menus 
  resources :users
  resources :sessions
  
  get "/login", to: "sessions#new"
  get "/logout", to: "sessions#destroy"
  
  root to: "foods#index"
end

app/models/criteria.rb
class Criteria < ActiveRecord::Base

  # belongs_to :food

end

app/models/food.rb
class Food < ActiveRecord::Base

  has_many :menus
  has_many :restaurants, :through => :menus
#  has_many :criteria
  has_many :ratings, :through => :menus
  
end

app/models/menu.rb
class Menu < ActiveRecord::Base

  belongs_to :restaurant
  belongs_to :food
  has_many :ratings
  # has_many :criteria, through: :foods  

end

app/models/preferences.rb
class Preferences < ActiveRecord::Base
end

app/models/rating.rb
class Rating < ActiveRecord::Base

  belongs_to :menu
  belongs_to :user
  
  validates_numericality_of :rating_stars, :only_integer => true, :allow_nil => true, :less_than_or_equal_to => 5,
        :message => "can only be whole number between 1 and 5."
  validates :menu_id, presence: true

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base

  has_many :menus
  # short circuit the join model to get rid of the menus in the middle so you don't need to loop through
  has_many :foods, :through => :menus
  has_many :ratings, :through => :menus

  # To decide how much information I want to require
  validates :name, presence: true
  validates :zip, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  has_many :users
  validates :email, presence: true
  # validates :password, presence: true - we can take this out since we have password_digest
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  # this runs before the action runds - we can call it what ever we want 
  # it runs before every action in every controller
  before_action :require_user
  
  def current_user
    User.find_by(id: session["user_id"])
  end

  def require_user
    if current_user.nil?
      redirect_to new_session_path, alert: "Please Login"
    end
  end    
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController

  skip_before_action :require_user, only: [:index, :show]

# Need to define the variable is in the controller, this method is called the action
# The index is a method in a controller mapping the db to the views 
  def index 
  # What's in between the def & the end is all the work
    @foods = Food.all
  end

  def show
    # Define the food as the what you clicked on 
    @food = Food.find_by(id: params["id"])
    # Now give me all the restaurants that have it
    @spots = @food.menus

    @rating = Rating.new
    @rest = @spots.restaurants
    # @food = Food.find_by(id: params["id"])
    # # give me the roles where the movie id = param
    # @availability = Menu.where(food_id: @food.id)
    # # We create an empty array and then... 
    # @spots = [] 
    # # ... loop through menus and add them to the array 
    # @availability.each do |spot|
    #   @spots << Restaurant.find_by(id: spot.restaurant_id)
    #end
  end 
  
  def new
    @food = Food.new
  end

  def create
    food_params = params.require(:food).permit(:category, :description)
    @food = Food.create(food_params)
    if @food.save
       redirect_to foods_path
     else
       render "fail"
    end
  end

  def edit
    @food = Food.find_by(id: params["id"])
  end

  def update
    food_params = params.require(:food).permit(:category, :description)
    @food = Food.find_by(id: params["id"])
    @food.update(food_params)
    redirect_to foods_path
  end

  def destroy
    @food = Food.find_by(id: params["id"])
    @food.destroy
    redirect_to foods_path
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController

  skip_before_action :require_user

# Need to define the variable is in the controller, this method is called the action
# The index is a method in a controller mapping the db to the views 
  def index 
    
  end

  def show
    @place = Menu.find_by(id: params["id"])

    # Find all the menus with the food id in params
    @ratings = Ratings.where(menu_id: params["id"])
    # give me the menus where the food id = param
    @availability = Menu.where(food_id: @food.id)
    # We creat an empty array and then... 
    @spots = [] 
    # ... loop through roles and add them to the array 
    @availability.each do |spot|
      @spots << Restaurant.find_by(id: spot.menu_id)
    end
    
    @ratings = Rating.where(menu_id: @spot.id)

  end 
  
  def new
  end

  def create

    Food.create(category: params["category"], description: params["description"])


  end

  def update
  end

  def destroy
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  skip_before_action :require_user

  def new
    # get my food
    @food = Food.find_by(id: params["food_id"])
    @spots = @food.restaurants
    @rating = Rating.new
    
  end

  def create
    @food = Food.find_by(id: params["food_id"])
   
    rating_params = params.require(:rating).permit!
    @rating = Rating.create(rating_params)
#   try to find the menu id that is for the selected restaurant
    @rating.user = current_user
    if @rating.save
      redirect_to foods_path notice: "Thanks for the review!"
    else
      render "new"
    end

  end


end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController


# Need to define the variable is in the controller, this method is called the action
# The index is a method in a controller mapping the db to the views 
  def index 
  # What's in between the def & the end is all the work
    @restaurants = Restaurant.all
  end

  def show
  end 
  
  def new
    @rest = Restaurant.new
  end

  def create
    rest_params = params.require(:restaurant).permit!
    @rest = Restaurant.create(rest_params)
    if @rest.valid?
      redirect_to restaurants_path, notice: "Cool Dude"
    else
      render "new", notice: "Sorry, it didn't save"
    end
  end

  def edit
    @rest = Restaurant.find_by(id: params["id"])
  end

  def update
    rest_params = params.require(:restaurant).permit!
    @rest = Restaurant.find_by(id: params["id"])
    @rest.update(rest_params)
    if @rest.valid?
      redirect_to restaurants_path, notice: @rest.name+" has been updated"
    else
      render "edit", notice: "Sorry, it didn't save"
    end
  end

  def destroy
    # this will need to be a complex link thing
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout false
  skip_before_action :require_user
 
  def create
    # Do authentication is there a user with this email and is the password correct
    user = User.find_by(email: params["email"])
    
    # ---- Alternative if you want to confirm both at the same time
    # if user && user.password == params["password"] 
    #   render text: "GREAT!"
    # else
    #   render text: "Nope - you fail"
    # end

    if user
      if user.authenticate(params["password"])
        session["user_id"] = user.id
        redirect_to root_path, notice: "GREAT! You're in the Secret Place!"
      else
        redirect_to root_path, alert: "Nope - you fail due to password"
      end
    
    else
      redirect_to root_path, alert: "Nope - you fail due to username"
    end
    
  end

  def destroy
    # Do sign-out
    session["user_id"] = nil
    redirect_to root_path, notice: "See ya Later!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :require_user

  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params["id"])
  end

  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit!
    @user = User.create(user_params)
    if @user.valid?
      redirect_to users_path, notice: "Cool Dude"
    else
      render "new"
    end
  end

  def edit
    @user = User.find_by(id: params["id"])
  end

  def update
    user_params = params.require(:user).permit!
    @user = User.find_by(id: params["id"])
    @user.update(user_params)
    redirect_to users_path
  end

  def destroy
    @user = User.find_by(id: params["id"])
    @user.destroy
    redirect_to users_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/monkeys_helper.rb
module MonkeysHelper
end

app/views/foods/edit.html.erb
<div class="jumbotron text-center">
  <h1> Edit Food & Beverage Categories </h1>
</div>

<p> <b><i> Again Bloody Marys are pretty much the only area with content at this point.... </i></b></p>

  <!-- Views should be the absolute minimal amount of ruby the what we put in the controll is the ACTION-->


<%= form_for @food do |form| %>
  <div class="form-group">
    <%= form.label :category %>
    <%= form.text_field :category, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class: "form-control" %>
  </div>
    <%= form.button 'Update Food', class: "btn btn-success" %>
<% end %>

app/views/foods/index.html.erb
<div class="jumbotron text-center">
  <h1> Food & Beverage Categories </h1>
</div>


<h4> Let's just focus on Bloody Marys at this point.  If you don't start your day off right, what's the point of starting it at all... </h4>

<p> <b><i> Also Bloody Marys are pretty much the only area with content at this point.... </i></b></p>

  <!-- Views should be the absolute minimal amount of ruby the what we put in the controll is the ACTION-->


<div class="row">
  <% @foods.each do |food| %>
  <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
           <i class="fa fa-star"></i>
        <div class="caption">
        <h3> <%= link_to food.category, food %></h3> 
          <p> <i> <%= food.description %> </i> </p>
          <p>
            <%= link_to "New Review", new_food_rating_path(food), class: "btn btn-primary" %>
            <%= link_to "Edit", edit_food_path(food), class: "btn btn-default" %> 
            <%= link_to "Delete", food_path(food), method: :delete, data: { confirm: 'Are you really really really sure?' }, class: "btn btn-default" %>
          </p>
        </div>
      </div>
    </div>
  <% end %>  
</div>

<!-- need to go in and remember how to add padding to this button to put it down below -->
  <td>
  <a href="foods/new" class="btn btn-primary">New Food</a>
</div>

app/views/foods/new.html.erb
<div class="jumbotron text-center">
  <h1> This is where we add new foods to track </h1>
</div>


<!-- This isn't working - I keep getting ActionController::Invalid AuthenticityToken in FoodsController#create  -->


<%= form_for @food do |form| %>
  <div class="form-group">
    <%= form.label :category %>
    <%= form.text_field :category, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class: "form-control" %>
  </div>
  <%= form.button 'Create Food', class: "btn btn-success" %>
<% end %>
<!--  placeholder: "Name of the Food or Drink Category"  -->

app/views/foods/show.html.erb
<div class="jumbotron text-center">
  <h1> You can find the best <%= @food.category %> at these fine establishments </h1>
</div>
<!-- Fix this below this show should reveal the list of restaruants that I can find the food selected -->

<div class="col-sm-12">
<h2>The <%= @food.category %> </h2>
  <p> <i> Description: <%= @food.description %> </i></p> 
 
<table class="table" >
  

  <span class="pull-right">
    <%= link_to "Rate a "+@food.category, new_rating_path, class: 'btn btn-sm btn-success' %>
    <% puts params.inspect %>
  </span>


  <%= form_for @rating do |form| %>
    <div class="form-group">

  <!-- These two should feed in from somewhere else, so they don't need to be inputs -->

    <div class="form-group">
        <%= form.label :menu_id %>
        <%= form.collection_select :menu_id, @restaurants, :id, :name, { include_blank: true }, { class: "form-control" } %>
      </div>
    
    <div class="form-group">
      <%= form.label :rating_stars %>
      <%= form.number_field :rating_stars, class: "form-control" %>
    </div>
    
    <div class="form-group">
      <%= form.label :comments %>
      <%= form.text_field :comments, class: "form-control" %>
    </div>
    <%= form.button 'Rate!', class: "btn btn-success" %>
  <% end %>
  </div>


  <h3> Restaurants </h3>

  <% @spots.each do |spot| %> 
  <tr>
  <td>
    <h4>  <%= link_to spot.id, ratings_path %> </h4>
    <h4>  <%= link_to spot.restaurant.name, ratings_path %> </h4>
    <p> <i>  Genre: <%= spot.restaurant.genre %> </i></p>
    <p>   Address: <br>
        <%= spot.restaurant.address %> <br>
        <%= spot.restaurant.city %>,
        <%= spot.restaurant.state %>
        <%= spot.restaurant.zip %></p>
<!--  run through and print each of the comments from the associated ratings -->
      <% spot.ratings.each do |review| %>
        <li> <%= review.comments %> </li>
      <% end %>
  </tr>
    <% end %>
    
</table>  

    <a href="http://localhost:3000/foods" class="btn btn-primary">Back to Foods</a>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>BestBloodyBuddy</title>
    <!-- Logo Font -->
    <link href="http://fonts.googleapis.com/css?family=Luckiest+Guy" rel="stylesheet" type="text/css">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <%= csrf_meta_tags %>
</head>

<body>
  <div class="container">

    <!-- Alerts -->
    <% if notice %>
      <div class="alert alert-success" role="alert"><%= notice %></div>
    <% end %>
    <% if alert %>
      <div class="alert alert-danger" role="alert"><%= alert %></div>
    <% end %>

<!-- Inserting the Navbar -->

<nav class="navbar navbar-default" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "BestBloody", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
            <ul class="nav navbar-nav">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> 
                  Menu 
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to "Foods", foods_path %></li>
                  <li><%= link_to "Restaurants", restaurants_path %></li>
                  <li><%= link_to "New Restaurant", new_restaurant_path %></li>
                  <li><%= link_to "New User", new_user_path %></li>
                  </ul>
              </li>
            </ul>
      
<!--       ID the user and create login/out functions -->
      <ul class="nav navbar-nav navbar-right">                 
        <li>
          <% if current_user %>
           <%= link_to "Logout", logout_path %>
          <% else %>
            <%= link_to "Login", login_path %>
          <% end %>          
        </li>
        <li>
          <a href="#">
            <i class="fa fa-user"></i>
              <% if current_user %>
                Hi, <%= current_user.try(:firstname) %>  
              <% else %>
                Guest
              <% end %>
          </a>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
  


<!--   Populate everything from individual pages -->  
  <div class="container">
      <%= yield %>
  </div>

</body>
</html>

app/views/menus/index.html.erb
<h3 class="page-header">
  Details about the menu (defined as the food/restaurant specific item)
  <span class="pull-right">
<!--  -->
  </span>
</h3>


<h1> TESTING -Need to do a lot of formatting - summary ratings on prior page, with more detail ratings hear?</h1>
<h4> <%= @place.restaurant.name %> </h4>

app/views/ratings/_form.html.erb
<%= form_for @rating do |form| %>
  <div class="form-group">

<!-- These two should feed in from somewhere else, so they don't need to be inputs -->

  <div class="form-group">
      <%= form.label :menu_id %>
      <%= form.collection_select :menu_id, @spots.order(:name), :id, :name, { include_blank: true }, { class: "form-control" } %>
    </div>
  
  <div class="form-group">
    <%= form.label :rating_stars %>
    <%= form.number_field :rating_stars, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= form.label :comments %>
    <%= form.text_field :comments, class: "form-control" %>
  </div>
  <%= form.button 'Rate!', class: "btn btn-success" %>
<% end %>
</div>

app/views/ratings/edit.html.erb
<h1>Trying to set up the ratings</h1>

<%= form_for @ratings do |form| %>
  <div class="form-group">
    
    <%= form.label :rating_stars %>
    <%= form.text_field :rating_stars, class: "form-control" %>
    <%= form.label :comments %>
    <%= form.text_field :comments, class: "form-control" %>
    <%= form.label :visit_date %>
    <%= form.text_field :visit_date, class: "form-control" %>
  </div>
  <%= form.button 'Update rating & comments', class: "btn btn-success" %>
<% end %>

app/views/ratings/index.html.erb
<h1 class="page-header">
  Trying to set up the ratings
  <span class="pull-right">
    <%= link_to "New Rating", new_rating_path, class: 'btn btn-sm btn-success' %>
  </span>
</h1>

<ul>
  <% @ratings.each do |rating| %>
    <li><%= rating.rating_stars %>, <%= rating.comments %>, 
        <%= link_to "Edit", edit_rating_path(rating), class: 'btn btn-sm'%>
        <%= link_to "Delete", rating_path(rating), method: :delete, data: {confirm: " Are you really sure!?"}, class: 'btn btn-sm'%>
    </li>
  <% end %>
</ul>

app/views/ratings/new.html.erb
<div class="col-sm-12">
<% if @rating.errors.any? %>
  <div class="alert alert-warning">
    <h2>Some errors kept this rating from being saved:</h2>
    <ul>
      <% @rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for [@food, @rating] do |f| %>
  <div class="form-group">
    <%= f.label :menu_id %>
    <%= f.collection_select :menu_id, @spots.order(:name), :id, :name, { include_blank: true }, { class: "form-control" } %>
  </div>
  <div class="form-group">
    <%= f.label :criteria_id %>
    <%= f.collection_select :criteria_id, Criteria.order(:criteria_desc), :id, :criteria_desc, { include_blank: true }, { class: "form-control" } %>
  </div>
  <div class="form-group">
    <%= f.label :rating_stars %>
    <%= f.select :rating_stars, [1,2,3,4,5], class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :comments %>
    <%= f.text_area :comments, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :visit_date %>
    <%= f.date_field :visit_date, class: "form-control" %>
  </div>
  <%= f.button 'Post Your Review', class: "btn btn-success" %>
<% end %>

app/views/ratings/show.html.erb
Trying to set up the ratings

<%= Rating.all %>

app/views/restaurants/edit.html.erb
<%= form_for @rest do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :city %>
    <%= form.text_field :city, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :state %>
    <%= form.text_field :state, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :zip %>
    <%= form.text_field :zip, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :genre %>
    <%= form.text_field :genre, class: "form-control" %>
  </div>
  <%= form.button 'Update', class: "btn btn-success" %>
<% end %>

app/views/restaurants/index.html.erb
<h3 class="page-header">
  All Restaurants
  <span class="pull-right">
    <%= link_to "New Restaurant", new_restaurant_path, class: 'btn btn-sm btn-success' %>
  </span>
</h3>


<ul>
  <% @restaurants.each do |list| %>
    <li><b><%= list.name %></b>
         <p><%= list.address %> <br>
         <%= list.city %>, <br><%= list.state %> <%= list.zip %> <br>
         <%= link_to "Edit", edit_restaurant_path(list) %> <%= link_to "Delete", restaurant_path(list), method: :delete, data: { confirm: 'Are you sure?' } %> </p></li>
  <% end %>
</ul>

app/views/restaurants/new.html.erb
<% if @rest.errors.any? %>
  <div class="alert alert-warning">
    <h2>This didn't save because:</h2>
    <ul>
      <% @rest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @rest do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :city %>
    <%= form.text_field :city, class: "form-control" %>
  </div>
<!--  Can I make this a state scroll thing?  -->
  <div class="form-group">
    <%= form.label :state %>
    <%= form.text_field :state, class: "form-control" %>
  </div>
<!-- Isn't there a way I could use the zip to populate, or tie this to Google Maps -->
  <div class="form-group">
    <%= form.label :zip %>
    <%= form.text_field :zip, class: "form-control" %>
  </div>
<!-- I also want to define my genres so there's a limit -->
  <div class="form-group">
    <%= form.label :genre %>
    <%= form.text_field :genre, class: "form-control" %>
  </div>
    <%= form.button 'Create New', class: "btn btn-success" %>
<% end %>

app/views/users/edit.html.erb
<%= form_for @user do |form| %>
  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :firstname %>
    <%= form.text_field :firstname, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :lastname %>
    <%= form.text_field :lastname, class: "form-control" %>
  </div>
  <%= form.button 'Update', class: "btn btn-success" %>
<% end %>

app/views/users/index.html.erb
<h3 class="page-header">
  All Users
  <span class="pull-right">
    <%= link_to "New User", new_user_path, class: 'btn btn-sm btn-success' %>
  </span>
</h3>


<ul>
  <% @users.each do |user| %>
    <li><b><%= user.name %></b>
         (<%= user.firstname %> <%= user.lastname %>) <br><%= user.email %> <%= link_to "Edit", edit_user_path(user) %> <%= link_to "Delete", user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<!-- 
  Finish the signup form
  Validate that the email, password, and name are present
-->

<% if @user.errors.any? %>
  <div class="alert alert-warning">
    <h2>Some errors kept this movie from being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @user do |form| %>
  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>
    <%= form.button 'Sign Up', class: "btn btn-success" %>
<% end %>